export const CREATE_TODO = 'CREATE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const DELETE_TODO = 'DELETE_TODO';

export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const TRIGGER_SNACKBAR = 'TRIGGER_SNACKBAR';
export const UNTRIGGER_SNACKBAR = 'UNTRIGGER_SNACKBAR';

export const TRIGGER_MODAL = 'TRIGGER_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
