export const CREATE_TODO = 'CREATE_TODO';
export const FETCH_TODOS = 'FETCH_TODOS';

export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const TRIGGER_SNACKBAR = 'TRIGGER_SNACKBAR';
export const UNTRIGGER_SNACKBAR = 'UNTRIGGER_SNACKBAR';
